lang: es
citeproc: true
bibliography: bibliografia.bib
csl: apa.csl

project:
  type: book
  output-dir: docs

website:
  reader-mode: true
  search:
    location: sidebar
    type: overlay
  comments:
    hypothesis: true

book:
  title: "Modelo Estocástico con Retraso para la Dinámica Fenológica de Vegetación"
  reader-mode: true
  favicon: figuras/unach.png
  cover-image: figuras/unach.png
  chapters:
    - index.qmd
    - capitulo_2.qmd
    - capitulo_3.qmd
    #- conclusiones.qmd
    - bibliografia.qmd

  sidebar:
    logo: figuras/unach.png
    search: true
    style: floating
    collapse-level: 2
    border: true
  
  open-graph: true
  twitter-card: true
  repo-url: https://github.com/carlos-e-chacon/Linear-SDDE
  repo-actions: [edit, issue, source]
  page-navigation: true
  downloads: 
    - pdf
  page-footer:
    left: "Carlos Eduardo Chacón Rodríguez"

comments:
  hypothesis: true

format:
  html:
    theme:
      dark: darkly
      light: cerulean
    toc: true
    toc-depth: 3
    grid:
      sidebar-width: 300px
      body-width: 900px
      margin-width: 300px
      gutter-width: 1.5rem
    code-copy: true
    code-overflow: wrap
    smooth-scroll: true
    link-external-newwindow: true
    css: styles.css
  
  pdf:  
    documentclass: book
    #include-in-header: latex/preamble.tex
    #include-before-body: latex/portada.tex
    #include-after-body: latex/hoja_final.tex
    titlepage: false
    toc: true
    number-sections: false
    mainfont: Latin Modern Roman
    fontsize: 12pt
    geometry: a4paper
    output-file: tesis_carlos_chacon
    dpi: 300
    fig-format: png
    link-citations: true
    urlcolor: blue 

execute:
  enabled: true
  engine: python
  echo: true       # Muestra el código fuente
  results: show    # Muestra los resultados formateados
  output: true     # Muestra la salida estándar
  warning: false   # Oculta advertencias (como DeprecationWarnings)
  message: false   # Oculta mensajes de carga de paquetes, etc.
  eval: true       # Asegura que el bloque se ejecute